name: testinggg
favicon: null
layout_spectrum: 0.21019650879316032
typography_spectrum: 0.8383124659303576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3ead9'
    - '#f1a1ae'
    - '#2a307a'
    - '#e06377'
    - '#7b739c'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
